//org table
CREATE TABLE organization(id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(64) NOT NULL UNIQUE, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

//user table
CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(64) NOT NULL UNIQUE, username VARCHAR(32) NOT NULL UNIQUE, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

//channel table
CREATE TABLE channel(id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(64) NOT NULL UNIQUE, organization_id INTEGER REFERENCES organization(id), created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated DEFAULT CURRENT_TIMESTAMP);

//message table
CREATE TABLE message (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT, user_id INTEGER REFERENCES user(id), channel_id INTEGER REFERENCES channel(id), created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

//user_channel table
CREATE TABLE user_channel(user_id INTEGER REFERENCES user(id), channel_id INTEGER REFERENCES channel(id));
